# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(686, 377)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lightLevel = QtWidgets.QCheckBox(self.centralwidget)
        self.lightLevel.setGeometry(QtCore.QRect(150, 130, 101, 21))
        self.lightLevel.setObjectName("lightLevel")
        self.beginButtom = QtWidgets.QPushButton(self.centralwidget)
        self.beginButtom.setGeometry(QtCore.QRect(260, 280, 141, 61))
        self.beginButtom.setObjectName("beginButtom")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 10, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 90, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.middleLevel = QtWidgets.QCheckBox(self.centralwidget)
        self.middleLevel.setGeometry(QtCore.QRect(150, 160, 91, 21))
        self.middleLevel.setObjectName("middleLevel")
        self.hardLevel = QtWidgets.QCheckBox(self.centralwidget)
        self.hardLevel.setGeometry(QtCore.QRect(150, 190, 81, 21))
        self.hardLevel.setObjectName("hardLevel")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(310, 90, 241, 171))
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 91, 21))
        self.label_3.setObjectName("label_3")
        self.maxNumber = QtWidgets.QLineEdit(self.widget)
        self.maxNumber.setGeometry(QtCore.QRect(110, 70, 113, 20))
        self.maxNumber.setObjectName("maxNumber")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(70, 20, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 81, 21))
        self.label_5.setObjectName("label_5")
        self.maxAttempts = QtWidgets.QLineEdit(self.widget)
        self.maxAttempts.setGeometry(QtCore.QRect(110, 120, 113, 20))
        self.maxAttempts.setObjectName("maxAttempts")
        self.userLevel = QtWidgets.QCheckBox(self.centralwidget)
        self.userLevel.setGeometry(QtCore.QRect(150, 220, 81, 21))
        self.userLevel.setObjectName("userLevel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lightLevel.setText(_translate("MainWindow", "Light Level"))
        self.beginButtom.setText(_translate("MainWindow", "Begin!"))
        self.label.setText(_translate("MainWindow", "Number Guessing Game"))
        self.label_2.setText(_translate("MainWindow", "Choose Level"))
        self.middleLevel.setText(_translate("MainWindow", "Middle Level"))
        self.hardLevel.setText(_translate("MainWindow", "Hard Level"))
        self.label_3.setText(_translate("MainWindow", "Max number"))
        self.label_4.setText(_translate("MainWindow", "Patameters"))
        self.label_5.setText(_translate("MainWindow", "Max attempts"))
        self.userLevel.setText(_translate("MainWindow", "User Level"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
